### PR TITLE
Add NFR and Glossary to developer guide

### LINKED ISSUE #68: Update User Guide
- [x] Fatin: 1, 2
- [x] YiJing: 3
- [x] Sam: 4.1 - 4.2
- [x] Gabe: 4.3
- [x] Rai: 4.4 - 4.7

### LINKED ISSUE #69: Update Developer Guide
- [x] A: YiJing
- [x] B: Rai
- [x] C: Gabe, Fatin
- [x] D, E: Sam

### PR DESCRIPTION
**Pull request by Eclmist**

### CODE REVIEW

**Review by fatin99 — DISMISSED** [review]
good changes :)

**Review by fatin99 — COMMENTED** [review]
made a mistake

**Review by fatin99 — APPROVED** [review]
All good

**Review by PotatoCombat — APPROVED** [review]
All good!

**Pull request merged**
