### PR TITLE
Edit documentations

### PR DESCRIPTION
**Pull request by chuayijing**
- Edit README.adoc
- Edit Appendix A of Developer Guide
- Edit Features of User Guide

### CODE REVIEW

**Review by fatin99 — APPROVED** [review]
Good changes :)

**Review by PotatoCombat — DISMISSED** [review]
All good!

**Review by PotatoCombat — COMMENTED** [review]
Think there some build errors actually

**Comment by PotatoCombat** [comment]
Closed PR due to missing Travis build

**Pull request closed without merging**
